### ISSUE TITLE
reports error for empty files

### ISSUE THREAD

**Issue by glensc** [danorton/php_replace_short_tags#1]
> $ touch test.php
> $ ls -l test.php 
> -rw-r----- 1 glen glen 0 jaan  19 17:05 test.php
> $ php-replace-short-tags  --overwrite test.php 
> Unable to read input file

expected:

>  $ php-replace-short-tags  --overwrite test.php 
> 0 changes

**Comment by danorton** [comment]
Merged to f7a7a1ec6d813450fb4424180ea982c7d1e36dce
