### ISSUE TITLE
<?= is not a short tag?

### ISSUE THREAD

**Issue by Goddard** [danorton/php_replace_short_tags#6]
I am under the impression that "<?=" is not a short tag.  That is just a quick way to echo things out.  The PHP 8 change has no effect on "<?="

**Comment by danorton** [comment]
It is a short tag, but specifically a short _echo_ tag. It is always available since PHP 5.4. The ``--skip-echo-tags`` option will insure that short echo tags remain unchanged.

See https://www.php.net/manual/en/language.basic-syntax.phptags.php
